### ISSUE TITLE
Unable to index (error with snakemake)

### ISSUE THREAD

**Issue by AyushSaxena** [EichlerLab/smrtsv2#16]
Hello,

I have been unable to get even the dry run working for me.  I have been informed by our cluster support (at the University of Florida) that the installation may have had glitches. In that light, the script I'm running is the following -
module load smrtsv2

${SMRT_DIR}/smrtsv.py \
--tempdir ${TMP} \
--dryrun \
--verbose \
run \
--batches 8 \
--threads 8 \
--species C.elegans \
--asm-polish arrow \
--min-support 3 \
--min-hardstop-support 3 \
${reference} \
${path_to_fasta}

The less verbose version of the error I'm getting is -
snakemake: error: unrecognized arguments: -T
Failed to index reference

I'm attaching the full (verbose) error report.  Is this a problem with the installation, or am I using it wrong?

Thank you
Ayush
[smrtsv2_32818810.txt](https://github.com/EichlerLab/smrtsv2/files/2922726/smrtsv2_32818810.txt)

**Comment by paudano** [comment]
There are two problems here.

1) I think you must have an old version of SMRT-SV. The `-T` option was removed a while ago. Newer versions of Snakemake no longer need it (it does timestamps by default now, which is what -T used to turn on).

2) Run the shell script `smrtsv` from the ${SMRT_DIR}, not the python file `smrtsv.py`. The shell script will setup the environment to find the snakemake install within the `dep` directory. Since you are running `smrtsv.py` directly, it's using the Snakemake and Python it  finds in your environment, which may create conflicts and may not have all the libraries installed that SMRT-SV uses.

Note: Installing SMRT-SV should not be glitchy. It's pretty well automated now. Pull the git repository, cd into `dep`, and run `make`. It shouldn't be dependent on much in your environment; it even uses the conda GCC installation.
